// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDFJOqJvcThEaZ0YyeFJnSXQTH7jnykcE',
    appId: '1:492222292903:web:9a9087d27a553022410c82',
    messagingSenderId: '492222292903',
    projectId: 'test-project-e6c3f',
    authDomain: 'test-project-e6c3f.firebaseapp.com',
    storageBucket: 'test-project-e6c3f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4rRgVVaDwg175CrPOnmOncvIVZku_SqA',
    appId: '1:492222292903:android:26038de96ae422b0410c82',
    messagingSenderId: '492222292903',
    projectId: 'test-project-e6c3f',
    storageBucket: 'test-project-e6c3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPEvmDejJCse-FoM799VB-HBYnYPwpK5M',
    appId: '1:492222292903:ios:ca211ac6ee82edfa410c82',
    messagingSenderId: '492222292903',
    projectId: 'test-project-e6c3f',
    storageBucket: 'test-project-e6c3f.appspot.com',
    iosClientId: '492222292903-ds8ho2tij7au6m1r7nv6l8ga9ogbgne9.apps.googleusercontent.com',
    iosBundleId: 'build.milk.authentication.milkAuthenticationFrameworkExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPEvmDejJCse-FoM799VB-HBYnYPwpK5M',
    appId: '1:492222292903:ios:ca211ac6ee82edfa410c82',
    messagingSenderId: '492222292903',
    projectId: 'test-project-e6c3f',
    storageBucket: 'test-project-e6c3f.appspot.com',
    iosClientId: '492222292903-ds8ho2tij7au6m1r7nv6l8ga9ogbgne9.apps.googleusercontent.com',
    iosBundleId: 'build.milk.authentication.milkAuthenticationFrameworkExample',
  );
}
